name: Test Model

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Download model artifact from Train workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: train-model.yml
          name: model
          path: .

      - name: Verify artifact downloaded
        run: |
          ls -lah
          ls -lah model/ || echo "model folder not found"

      - name: Run Model Inference Test
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
