name: Test Model

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Download model artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: train-model.yml
          name: model
          path: model
          repo: ${{ github.repository }}
          branch: main
          run_id: ${{ github.event.workflow_run.id }}

      - name: List downloaded files
        run: |
          echo "Current directory:"
          ls -lah
          echo "Model directory:"
          ls -lah model/

      - name: Run Model Inference Test
        uses: lasselundstenjensen/itu-sdse-project-model-validator@main
